name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
     - name: Print greeeting
       run: echo "Hello World!"
     - name: Print goodbye
       run: echo "Done - bye!"
